name: main

on:
  push:
    tags:
      - v*
    branches:
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.3"
      - name: Add libvips backports PPAs
        run: sudo add-apt-repository -y ppa:strukturag/libde265 && sudo add-apt-repository -y ppa:strukturag/libheif && sudo add-apt-repository -y ppa:tonimelisma/ppa
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsqlite3-dev libvips-dev
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.3"
      - name: Add libvips backports PPAs
        run: sudo add-apt-repository -y ppa:strukturag/libde265 && sudo add-apt-repository -y ppa:strukturag/libheif && sudo add-apt-repository -y ppa:tonimelisma/ppa
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsqlite3-dev libvips-dev
      - name: Build
        run: make build
      - name: Test
        run: go test -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=meteorae
            -Dsonar.projectKey=meteorae_server
            -Dsonar.javascript.lcov.reportPaths=coverage.lcov
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.3"
      - name: Add libvips backports PPAs
        run: sudo add-apt-repository -y ppa:strukturag/libde265 && sudo add-apt-repository -y ppa:strukturag/libheif && sudo add-apt-repository -y ppa:tonimelisma/ppa
      - name: Install dependencies
        run: sudo apt update && sudo apt install libsqlite3-dev libvips-dev
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Build
        run: make build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
